services:
  - type: web
    name: walmart-sales-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app/app.py --server.port=10000
    envVars:
      - key: DB_URL
        value: mysql+mysqlconnector://sql12788463:vwckZ4Bt7u@sql12.freesqldatabase.com:3306/sql12788463
